version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd client && npm install  # Install dependencies for the frontend
      - npm install  # Install dependencies for the backend
  build:
    commands:
      - echo Building frontend...
      - cd client && npm run build  # Build the frontend (React)
      - cd..
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - '**/*'  # Include all files in the artifact
    - '!node_modules/**'  # Exclude node_modules
  base-directory: client/build # Assuming your frontend output is in client/build
