version: 0.2

phases:
  install:
    commands:
      - echo Installing backend dependencies...
      - npm install
      - echo Installing frontend dependencies...
      - cd client
      - npm install
      - cd..
  build:
    commands:
      - echo Build started on `date`
      - cd client
      - npm run build
      - cd ..
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - '**/*'  # Include all files in the artifact
    - '!node_modules/**'  # Exclude node_modules
  base-directory: client/build # Assuming your frontend output is in client/build
